# Generated by Django 6.0.6 on 2026-06-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airqualityreading',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='airqualityreading',
            constraint=models.UniqueConstraint(fields=('station', 'timestamp'), name='unique_station_timestamp'),
        ),
    ]
